apiVersion: apps/v1
kind: Deployment
metadata:
  name: testservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testservice
  template:
    metadata:
      labels:
        app: testservice
    spec:
      serviceAccountName: orionpy-test
      containers:
        - name: testservice
          image: testservice
          ports:
            - containerPort: 3000
              name: http
        - name: rhea
          image: junoinnovations/rhea:v1.0.0
          env:
            - name: LOGLEVEL
              value: debug
          ports:
            - containerPort: 13000
              name: auth
          volumeMounts:
            - name: policies
              mountPath: /etc/rhea/policies
              readOnly: true
      volumes:
        - name: policies
          configMap:
            name: rhea-policies
