name: Microservice CI
on:
  workflow_dispatch:
  workflow_call:

jobs:
  QC:
    uses: juno-fx/Orion-Py/.github/workflows/ms-qc.yml@10-enable-ci
    secrets: inherit
  Test:
    needs:
      - QC
    uses: juno-fx/Orion-Py.github/workflows/ms-test.yml@10-enable-ci
    secrets: inherit
